default:
  # Outgoing emails configuration (see examples above)
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: "smtp.sendgrid.net" 
      port: 25
      authentication: :login
      domain: "heroku.com" 
      user_name: "SENDGRID_USERNAME" 
      password: "SENDGRID_PASSWORD" 
